services:
  backend:
    image: 234774/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://quanlysinhvien:Mongo123@Cluster0.tscun0u.mongodb.net/cloud_lab?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    image: 234774/mern-frontend:1.0
    ports:
      - "3000:80"
